/**
 * Author:  johan
 * Created: 2018-jan-28
 */

DROP TABLE CHAPTER;
DROP TABLE PERSONAL_INFO;
DROP TABLE USERS;
DROP TABLE ANSWER;
DROP TABLE QUESTION;
DROP TABLE QUIZ;
DROP TABLE SUBJECT;


/**
 * THE DATABASE STORES DIFFERENT SUBJECTS with some introductionary description 
 * of the subject.
 */
CREATE TABLE SUBJECT (
    SUBJECT_ID  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),  
    SUBJECT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION_HTML LONG VARCHAR NOT NULL,
    PRIMARY KEY (SUBJECT_ID)
);

/**
 * Chapters is a subsection of a subject. The priority desides the order of the  
 * chapters.
 */
CREATE TABLE CHAPTER (
    CHAPTER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SUBJECT_ID INTEGER NOT NULL REFERENCES SUBJECT(SUBJECT_ID),
    CHAPTER_NAME VARCHAR(100) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    HTML_CONTENT LONG VARCHAR NOT NULL,
    CONSTRAINT primary_key_chapters PRIMARY KEY(CHAPTER_ID)
);


/**
 * Application has registered users.
 */
CREATE TABLE USERS(
    USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    UNIQUE(USER_NAME),
    PRIMARY KEY(USER_ID) 
);

/**
 * Each user has som personal info.
 */
CREATE TABLE PERSONAL_INFO(
    USER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID),
    FIRST_NAME VARCHAR(256),
    LAST_NAME VARCHAR(256),
    MIDDLE_NAME VARCHAR(256),
    EMAIL VARCHAR(256),
    COUNTRY VARCHAR(100),
    STREET_ADDRESS VARCHAR(100),
    CITY VARCHAR(256),
    POSTAL_CODE VARCHAR(16),
    PRIMARY KEY(USER_ID)
);


/** 
 * The application has quizzes.
 */
CREATE TABLE QUIZ(
    QUIZ_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SUBJECT_ID INTEGER NOT NULL REFERENCES SUBJECT(SUBJECT_ID),
    QUIZ_NAME VARCHAR(100),
    PRIMARY KEY(QUIZ_ID)
);


/**
 * Questions for a quizz.
 */
CREATE TABLE QUESTION(
    QUESTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    QUIZ_ID INTEGER REFERENCES QUIZ(QUIZ_ID),
    QUESTION_TEXT LONG VARCHAR NOT NULL,
    PRIMARY KEY(QUESTION_ID)
);

/**
 * Anwers to a question true or false
 */
CREATE TABLE ANSWER(
    ANSWER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    QUESTION_ID INTEGER NOT NULL REFERENCES QUESTION(QUESTION_ID),
    ANSWER_TEXT LONG VARCHAR NOT NULL,
    TRUTH_VALUE BOOLEAN NOT NULL,
    PRIMARY KEY(ANSWER_ID)
);

